[package]
name = "rust-build-release-test"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/d-strobel/rust-build-release-test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
